# Che-Theia workflow

dist: focal
os: linux
cache: false
git:
  depth: false 

language: node_js
node_js: "12"

install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker login quay.io -u="$QUAY_USERNAME " -p="$QUAY_PASSWORD"

before_script:
  - chmod +x .travis/*

env: 
  global:
  - TAG=next
  - CDN_PREFIX=https://static.developers.redhat.com/che/theia_artifacts/
  - MONACO_CDN_PREFIX=https://cdn.jsdelivr.net/npm/
  - RECREATE_TAGS=false
  - PUSH_TO_NPMJS=true 

jobs:
  include: 
    #happy-path
    - &happy-path
      name: happy-path (alpine, next)
      install: skip
      cache: 
        - npm: true
        - yarn: true
      env: DIST=alpine CHECTL_CHANNEL=next MINIKUBE_VERSION=v1.18.1
      arch: amd64
      script: ./.travis/happy-path.sh


